#!/usr/bin/bash

### $1 : GENETIC DATA PATH - PLINK data
### $2 : WEIGHTS PATH - PRS based on known genetic variants, unique to this pipeline
### $3 : OUTPUT PREFIX

### ASSIGN MEANINGFUL VARIABLE NAMES TO COMMAND LINE VARIABLES

# Path of genetic data
GENETICDATA=$1

# Path of weightings file Should be tab delimited:
WEIGHTS=$2
# Get variant count in weightings file
WEIGHTS_COUNT=`wc -l ${WEIGHTS} | awk '{print $1}'`

OUT=$3

echo "Creating new input files in the required Plink format."

echo "Performing PLINK-based GRS generation"

## 1. Define path to PLINK program executable
PLINK=/slade/home/rw673/prs_generating_tool/executables/plink


## 2. FILE FORMATTING HERE SPECIFIC TO PLINK PRS GENERATION
##    Note, no phenotype or summary stats required for PLINK PRS generation
##    Only correct genetic data and weight file

### a. Format weightings file to be chr:pos | WEIGHTED_ALLELE | WEIGHT
echo "Formatting weightings file for plink"
awk 'BEGIN{OFS="\t"}{print $1":"$2, $3, $5}' $WEIGHTS > plink.weights.temp


### b. The .bim file contains rsids as second column not chr:pos so lets archive the original bed and up$
echo "Formatting .bim file to match weightings file IDs based on chr:pos"
#### put aside original bim file by renaming it
cp ${GENETICDATA}.bim ${GENETICDATA}.bim.orig
#### read the original bim file back but outputting chr (col1) and pos (col4)  into column 2 as chr:pos
awk 'BEGIN{OFS="\t"}{print $1, $1":"$4, $3, $4, $5, $6}' ${GENETICDATA}.bim.orig  > ${GENETICDATA}.bim


## 3. Run plink to generate the PRS
echo "Running PLINK..."
$PLINK \
  --bfile $GENETICDATA \
  --score plink.weights.temp \
  --out $OUT

sed -i 's/ \+ /\t/g' ${OUT}.profile
perl -pe 's/^\s+//' ${OUT}.profile > ${OUT}.profile.txt
echo "PLINK PRS output to ${OUT}.profile.txt"



## 4. Clean up any files generated by script and no longer needed
echo "Cleaning up..."
# Remove file specific to this part of pipeline
rm plink.weights.temp
# Restore original bim file
mv ${GENETICDATA}.bim.orig ${GENETICDATA}.bim


echo "PLINK ANALYSIS DONE"

### END OF PLINK-BASED ANALYSIS ###
